### ISSUE TITLE
Publish latest versions to NPM

### ISSUE THREAD

**Issue by jhesgodi** [prismicio/prismic-javascript#166]
Hello,

The latest versions of the package are not updated in npm, which is now behind at `v3.0.2`
Is this expected to be fixed soon? 

My team has a PRISMIC platinum account and we are blocked by a bug ([commit ref](https://github.com/prismicio/prismic-javascript/commit/db60da93fbd0dcc61f04a92c856d8d9f92f5cd38)) that was addressed in recent versions.

**NPM**
https://www.npmjs.com/package/prismic-javascript
![image](https://user-images.githubusercontent.com/2966156/117901933-c1121080-b30f-11eb-9d2b-79ee387453ab.png)
**GITHUB**
![image](https://user-images.githubusercontent.com/2966156/117901976-d850fe00-b30f-11eb-90de-39187f19ce3a.png)

Thanks for checking.

**Comment by angeloashmore** [comment]
Hi @jhesgodi, the package was renamed from `prismic-javascript` to `@prismicio/client`.

You can find the latest versions in the renamed package.

https://www.npmjs.com/package/@prismicio/client

## To update your project:

First, install the new package and uninstall the previous one.

```sh
npm install @prismicio/client
npm uninstall prismic-javascript
```

Or if you use Yarn:

```sh
yarn add @prismicio/client
yarn remove prismic-javascript
```

Then in your project, replace any references to `prismic-javascript` with `@prismicio/client`. Because updates have been made to library since the latest `prismic-javascript` release, please check your project for any changes that may be required due to the update.

I'm going to close this issue, but feel free to continue the conversation here if you are running into issues with the change. Thanks!
