### ISSUE TITLE
[v6] Specifying routes in defaultParams is unintuitive

### ISSUE THREAD

**Issue by samlfair** [prismicio/prismic-javascript#189]
I mentioned this to @lihbr. When you init your client, you have to pass your options inside a `defaultParams` argument. It makes sense for some options, like `orderings`, where you might want to have a default that you can override. But other options, like `routes`, aren't defaults — they're global. It would be nice to be able to specify routes directly in the options, like this:
```js
import {createClient, getEndpoint} from '@prismicio/client'
const repoName = 'your-repo-name'
const options = {
  routes: [
    {
      type: 'page',
      path: '/'
    }
  ]
}
const endpoint = getEndpoint(repoName)
const client = createClient(endpoint, options)
const promise = client.getAll()
```
(I might be misunderstanding! Forgive me if so.)

**Comment by angeloashmore** [comment]
I agree; making `routes` a top-level configuration property makes it more intuitive. It should still be overridable per-query, but doing so would be rare.

What @lihbr said is true. `routes` are just another parameter. Same for `accessToken` and `ref`, but we give those special priority since they are unlikely to be overridden and have a big effect on the query results.

I made the change so `routes` is now a top-level option (commit: https://github.com/prismicio/prismic-javascript/commit/69f2002a97c476bc7b7f9161ee81946f9e65a4c9).

**Published in `v6.0.0-alpha.11`**

---

P.S. When documenting client creation, it could be beneficial to guide users to write the options within the `createClient()` call. Their editor will display the correct TypeScript types while writing their options which could lead to less errors.

```ts
import { createClient, getEndpoint } from '@prismicio/client'

const repoName = 'your-repo-name'
const endpoint = getEndpoint(repoName)
const client = createClient(endpoint, {
  // When the user begins typing "routes", ts-server can
  // provide a suggestion with inline documentation.
  routes: [
    {
      type: 'page',
      path: '/'
    }
  ]
})
const promise = client.getAll()
```
