### ISSUE TITLE
Update README to remove depreacted api method

### ISSUE THREAD

**Issue by IikkaWinter** [prismicio/prismic-javascript#98]
After intensive debugging as to why we were seeing random 403 responses from prismic API, I finally stumbled upon [this documentation](https://prismic.io/docs/reactjs/query-the-api/how-to-query-the-api) that recommends using `client` method instead of the deprecated `api` method. I am not sure yet if this will fix the issues we've had but at least the repository documentation should be up to date.

**Comment by hypervillain** [comment]
Hey @IikkaWinter, don't take my word for granted but I think "deprecated" is a strong term here, you can definitely keep using `api` in your projects.

As to the errors you encounter, do you happen to cache your Prismic refs or the result of your calls to `api`?

**Comment by IikkaWinter** [comment]
Not my words. It says "The API method (deprecated)" in the documentation I linked.

What comes to the issues, we still do see the 403 errors every now and then. Should we always declare the client before a new request is made to fetch data with `const client = Prismic.client(apiEndpoint)`?

**Comment by srenault** [comment]
Indeed **deprecated** is strong word here. I would say if you're working on a Single Page App, the preferable way is to use the _client_ api. If you're using a this kit on server side (node), you have to use the _api_ function if you want to have the preview.
The _client_ api is just a wrapper around the _api_ function (The _client_ api doesn't provide any way of passing the node request so we can read the preview cookie).
We created the `client` api because a lot of people had some issues because they store the _api_ object once. It's ending up with outdated master ref and misleading error message (forbidden error).
We're going to work on that soon in order to unify everything (through the _client_ api).

**Comment by IikkaWinter** [comment]
@srenault thanks for the response. If you feel like **deprecated** is too strong of a word, maybe take it out of your documentation then. ;) 

We actually have a nextjs (SSR) app and as far as I can see the issues we are (still) facing are caused by an old master ref in cases where the initial document is served from cache and the CMS contents have been published in between. Which approach would you suggest to take here?
